#!/bin/bash

prefix=/usr/local
exec_prefix=/usr/local

args=$*

for arg in $args
do
	case $arg in
	"--libs")
		echo "-L$prefix/lib -lKhagine -lm -lpthread"
	;;
	"--cflags")
		echo "-O2 -Wall -pipe -g -I$prefix/include -I$prefix/include/Khagine"
	;;
	esac
done
